# Generated by Django 4.1.3 on 2022-12-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_projects_visited_count', 'view projects visited count'),)},
        ),
    ]
